name: "Wait For It"

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  wait-for-it:
    name: "Is It Waiting?"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Wait For Google
        id: shouldSucceed
        uses: ./
        with:
          host: www.google.com
          port: 80
          timeout: 5

      - name: Wait For Google - Invalid Port
        id: shouldFail
        uses: ./
        with:
          host: www.google.com
          port: 80
          timeout: 5
        continue-on-error: true

      - name: Verify failure
        if: steps.shouldFail.outcome != 'failure'
        run: exit 1
